config/routes.rb
Rails.application.routes.draw do

  # Set Project Root Path #
  root 'static_pages#home'

  # Set Static Page Paths #
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/subscribe',   to: 'static_pages#subscribe'

  # Set Babies Paths #
  get    '/signup',   to: 'babies#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

  # Set Project CHat Rooms #
  get '/text',        to: 'rooms#show'


  # Set Project Resources #
  resources :babies
  resources :microposts,          only: [:create, :destroy]

  # Set Mounting for Chat Features #
  mount ActionCable.server => '/cable'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_baby.microposts.build
      @feed_items = current_baby.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def subscribe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">About MyDaddy</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    The <b><u><i>MOST SECURED</i></u></b> Sugar Daddy & Sugar Momma Website!<br/>
    <br/>
    Discover where we came from, where we are heading, and why you should make the switch to MyDaddy for all of your Sugar Needs!
  </h2>
  <h2>
    <table border="0" text-align="center" style="margin: 0 auto">
      <tr>
        <td style="padding: 10px;">
          <%= link_to "Sugar Adult Signup", '#', class: "btn btn-primary btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
        <td style="padding: 10px;">
          <%= link_to "Sugar Baby Signup", signup_path, class: "btn btn-success btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
      </tr>
    </table>
  </h2>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">Contact MyDaddy</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    We appreciate your interest in MyDaddy!<br/>
    <br/>
    Please use the following form to contact us and we will be in touch shortly!
  </h2>
  <h2>
    <table border="0" text-align="center" style="margin: 0 auto">
      <tr>
        <td style="padding: 10px;">
          <%= link_to "Sugar Adult Signup", '#', class: "btn btn-primary btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
        <td style="padding: 10px;">
          <%= link_to "Sugar Baby Signup", signup_path, class: "btn btn-success btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
      </tr>
    </table>
  </h2>  
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">Help for MyDaddy</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    The <b><u><i>MOST SECURED</i></u></b> Sugar Daddy & Sugar Momma Website!<br/>
    <br/>
    This page will guide you through the ins & outs for guiding you through the website.<br/>
    Discover how to easily create an account, update your profile, and connect with other Sugar users!
  </h2>
  <h2>
    <table border="0" text-align="center" style="margin: 0 auto">
      <tr>
        <td style="padding: 10px;">
          <%= link_to "Sugar Adult Signup", '#', class: "btn btn-primary btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
        <td style="padding: 10px;">
          <%= link_to "Sugar Baby Signup", signup_path, class: "btn btn-success btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
      </tr>
    </table>
  </h2>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/baby_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>


<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">Welcome to MyDaddy</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    The <b><u><i>MOST SECURED</i></u></b> Sugar Daddy & Sugar Momma Website!<br/>
    Connecting Sugar Babbies Safely & Securely with Sugar Daddies & Sugar Momma's!
  </h2>
  <h2>
    <table border="0" text-align="center" style="margin: 0 auto">
      <tr>
        <td style="padding: 10px;">
          <%= link_to "Sugar Adult Signup", '#', class: "btn btn-primary btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
        <td style="padding: 10px;">
          <%= link_to "Sugar Baby Signup", signup_path, class: "btn btn-success btn-lg", style: "font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
        </td>
      </tr>
    </table>
  </h2>
</div>
<table border="0" style="margin-left: auto; margin-right: auto" text-align="center" >
  <tr>
    <td style="padding: 10px; text-align: center">
      <h3 style="font-family: 'Inconsolata', monospace; color: #000; font-size: 20px;">Powered By:</h3>
    </td>
    <td style="padding: 10px; text-align: center">
      <h3 style="font-family: 'Inconsolata', monospace; color: #000; font-size: 20px;">Designed By:</h3>
    </td>
  </tr>
  <tr>
    <td style="padding: 10px;">
      <%= link_to image_tag("rails.svg", alt: "Rails Logo", width: "150"), "https://rubyonrails.org/", target: :_blank %>
    </td>
    <td style="padding: 10px;">
      <%= link_to image_tag("bio_hck_wlp.jpg", alt: "B10 H4ck3r", width: "100", height: "100", style: "border-radius: 75px"), "https://twitter.com/B10H4ck3r", target: :_blank %>
    </td>
  </tr>
</table>

<% end %>

app/views/static_pages/subscribe.html.erb
<% provide(:title, "Subscribe") %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">About MyDaddy</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    Subscription <strong>TERMS & CONDITIONS</strong> agreement!<br/>
    <br/>
    In order to provide you, The Sugar Baby, with all of the abilities of MyDaddy website, you
    will need to obtain a Subscription Module! Please Review the Subscription Terms & Conditions
    below for a full concept of how our site operates!<br/>
    <br/>
    <strong><u>Basic Membership</u></strong><br/>
    <i>
      With our Basic Membership, you will be able to enjoy these Benefits:<br/>
      * Date Sugar Adults!<br/>
      * Text Sugar Adults!<br/>
      * 95% Commission!<br/>
    </i>
    <strong><u>Pro Membership</u></strong><br/>
    <i>
      With our Pro Membership, you will be able to enjoy these Benefits:<br/>
      * Date Sugar Adults!<br/>
      * Text Sugar Adults!<br/>
      * 98% Commission!<br/>
    </i>
    <strong><u>Combo Memberships</u></strong><br/>
    <i>
      With our Combo Membership, you will be able to enjoy these Benefits:<br/>
      * Date Sugar Adults!<br/>
      * Text Sugar Adults!<br/>
      * 98% Commission!<br/>
    </i><br/>
    <% if logged_in? %>
    <%= link_to "Subscribe Now!", edit_baby_path(current_baby) %>
    <% end %>
  </h2>
</div>