config/routes.rb
Rails.application.routes.draw do

  # Set Project Root Path #
  root 'static_pages#home'

  # Set Static Page Paths #
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/subscribe',   to: 'static_pages#subscribe'

  # Set Babies Paths #
  get    '/signup',   to: 'babies#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

  # Set Project CHat Rooms #
  get '/text',        to: 'rooms#show'


  # Set Project Resources #
  resources :babies
  resources :microposts,          only: [:create, :destroy]

  # Set Mounting for Chat Features #
  mount ActionCable.server => '/cable'

end

app/models/baby.rb
class Baby < ApplicationRecord

  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :date_price, presence: true, length: { minimum: 5 }, allow_nil: true
  validates :text_price, presence: true, length: { minimum: 5 }, allow_nil: true
  validates :sex, presence: true, length: { maximum: 10 }, allow_nil: true
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # Returns the hash digest of the given string.
  def Baby.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Baby.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = Baby.new_token
    update_attribute(:remember_digest, Baby.digest(remember_token))
    remember_digest
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end

  def feed
    Micropost.where("baby_id = ?", id)
  end


end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController

  before_action :logged_in_baby, only: [:index, :edit, :update, :destroy]
  before_action :correct_baby,   only: [:edit, :update]
  before_action :admin_baby,     only: :destroy


  def index
    @babies = Baby.paginate(page: params[:page])
  end

    def show
      @baby = Baby.find(params[:id])
      @microposts = @baby.microposts.paginate(page: params[:page])
    end

    def new
      @baby = Baby.new
    end

    def create
      @baby = Baby.new(baby_params)
      if @baby.save
        reset_session
        log_in @baby
        flash[:success] = "Welcome to MyDaddy!"
        redirect_to @baby
      else
        render 'new'
      end
    end

    def edit
      @baby = Baby.find(params[:id])
    end

    def update
      @baby = Baby.find(params[:id])
      if @baby.update(baby_params)
        flash[:success] = "Profile updated"
        redirect_to @baby
      else
        render 'edit'
      end
    end

    def destroy
      Baby.find(params[:id]).destroy
      flash[:success] = "Sugar Baby deleted"
      redirect_to babies_url
    end

    private

      def baby_params
        params.require(:baby).permit(:name, :email, :password, :password_confirmation, :date_price, :text_price, :sex)
      end

      # Confirms a logged-in user.
      def logged_in_baby
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

      # Confirms the correct user.
      def correct_baby
        @baby = Baby.find(params[:id])
        redirect_to(root_url) unless current_baby?(@baby)
      end

      # Confirms an admin user.
      def admin_baby
        redirect_to(root_url) unless current_baby.admin?
      end

end

app/helpers/babies_helper.rb
module BabiesHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(baby, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(baby.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: baby.name, class: "gravatar")
  end

end

app/views/babies/_user.html.erb
<li>
  <%= gravatar_for baby, size: 50 %>
  <%= link_to baby.name, baby %>
</li>

app/views/babies/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @baby, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :sex %>
        <%= f.text_field :sex, class: 'form-control', placeholder: 'Male | Female | Other' %>

        
        <%= f.label :date_price %>
        <%= f.text_field :date_price, class: 'form-control', placeholder: '$' %>

        <%= f.label :text_price %>
        <%= f.text_field :text_price, class: 'form-control', placeholder: '$' %>
        <p class="note_txt">
          Please Send Email with: <br/>Text Price ~ $0.00 | Date Price ~ $0.00<br/> in order to generate your PayPal Button!<br/>
          Please Use the Exact Price You Are Using Above!
        </p>
        <table border="3px" style="margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px; box-shadow: 5px 5px 8px #9400D3">
          <tr>
            <td>
              <p>Basic Subscription</p>
            </td>
            <td>
              <p>Pro Subscription</p>
            </td>
            <td>
              <p>Combo Subscription</p>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "Basic Subscribe Terms", subscribe_path %>
            </td>
            <td>
              <%= link_to "Pro Subscribe Terms", subscribe_path %>
            </td>
            <td>
              <%= link_to "Combo Subscribe Terms", subscribe_path %>
            </td>
          </tr>
          <tr>
            <td>
              <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="VR5UDVB9VLZP6">
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribe_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
              </form>
            </td>
            <td>
              <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="E4WYAS2THE338">
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribe_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
              </form>
            </td>
            <td>
              <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="84BAGWQ8TPHK8">
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribe_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
              </form>
            </td>
          </tr>
        </table>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>

      <div class="gravatar_edit">
        <%= gravatar_for @baby %>
        <a href="https://gravatar.com/emails" class="grvt_txt" target="_blank">Change Your Gravatar Here!</a>
      </div>
    </div>
  </div>
</div>

app/views/babies/index.html.erb
<% provide(:title, 'All babies') %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">

  <%= will_paginate %>

  <ul class="babies">
    <% @babies.each do |baby| %>
      <li>
        <%= gravatar_for baby, size: 50 %>
        <%= link_to baby.name, baby, class: 'admin_view' %>
        <% if current_baby.admin? && !current_baby?(baby) %>
          | <%= link_to "delete", baby, method: :delete, data: { confirm: "You sure?" }, class: 'admin_delete' %>
          | <%= link_to "pause", baby, method: '#', data: { confirm: "Pause User?" }, class: 'admin_pause' %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <%= will_paginate %>

</div>

app/views/babies/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <h1 style="font-family: 'Dancing Script', cursive; color: #FFF;">MyDaddy Signup</h1>
  <h2 style="font-family: 'Sansita Swashed', cursive; text-align: center; font-size: 25px; color: #000">
    <br/>
    <%= form_with(model: @baby, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </h2>
</div>

app/views/babies/show.html.erb
<% provide(:title, @baby.name) %>
<div class="center jumbotron" style="box-shadow: 8px 8px 10px #F0F; border: 5px solid #000; background-color: rgba(255,192,203,0.8)">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @baby %>
          <p style="font-family: 'Sansita Swashed', cursive; font-size: 25px"><%= @baby.name %></p>
          <p style="font-family: 'Sansita Swashed', cursive; font-size: 20px"><%= @baby.sex %></p><br/>
          <p style="font-family: 'Sansita Swashed', cursive; font-size: 20px"><%= link_to 'Chat!', text_path %>
          <table border="3px">
            <tr>
              <td>
                <p style="font-family: 'Piazzolla', serif; font-size: 20px;"><b>Date Me:$</b><u><i><%= @baby.date_price %></i></u><b>&nbsp; Per Hour</b></p>
              </td>
              <td>
                <p style="font-family: 'Piazzolla', serif; font-size: 20px;"><b>Text Me: $</b><u><i><%= @baby.text_price %></i></u><b>&nbsp; Per Hour</b></p>
              </td>
            </tr>
            <tr>
              <td>
                <%= render 'babies/paypal_functions/discover_user_date' %>
              </td>
              <td>
                <%= render 'babies/paypal_functions/discover_user_text' %>
              </td>
            </tr>
          </table>
        </h1>
      </section>
    </aside>
    <div class="col-md-8">
      <% if @baby.microposts.any? %>
        <h3>Microposts (<%= @baby.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
      <% end %>
    </div>

  </div>
</div>