config/routes.rb
Rails.application.routes.draw do

  # Set Project Root Path #
  root 'static_pages#home'

  # Set Static Page Paths #
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/subscribe',   to: 'static_pages#subscribe'

  # Set Babies Paths #
  get    '/signup',   to: 'babies#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

  # Set Project CHat Rooms #
  get '/text',        to: 'rooms#show'


  # Set Project Resources #
  resources :babies
  resources :microposts,          only: [:create, :destroy]

  # Set Mounting for Chat Features #
  mount ActionCable.server => '/cable'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small  style="background-color: rgba(0,0,0,0.8)">
    <h3 style="color: #FFF; font-family: 'Sansita Swashed', cursive; font-size: 20px;">This Site Is Designed & Built By: <%= link_to "B10 H4ck3r", 'https://twitter.com/B10H4ck3r', target: :_blank, style: "color: #0F0" %></h3>
  </small>
  <nav  style="background-color: rgba(0,0,0,0.8)">
    <ul>
      <li><%= link_to "About",   about_path, style: "color: #0F0; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
      <li><%= link_to "Contact", contact_path, style: "color: #0F0; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: pink">
  <div class="container">
    <%= link_to "MyDaddy", root_path, id: "logo", style: "color: purple; font-family: 'Playfair Display', serif;" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
        <li><%= link_to "Help", help_path, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" , style="color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_baby, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
              <li><%= link_to "Settings", edit_baby_path(current_baby), style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %>
              </li>
              <li class="divider"></li>
              <% if current_baby.admin? %>
                <li><%= link_to "Users", babies_path, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, style: "color: green; font-family: 'Sansita Swashed', cursive; font-size: 20px;" %></li>
        <% end %>
      </ul>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Indie+Flower&family=Lobster&family=Playfair+Display:ital@0;1&family=Sansita+Swashed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata&family=Libre+Baskerville&family=Piazzolla:wght@100&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>